sudo: required

services:
  - docker

language: python

python:
  - 2.7
  - 3.6

cache: pip

install:
  - pip install -r build-requirements.txt && pip install -r requirements.txt

script:
  - coverage run -m unittest discover -f && coverage report -m --skip-covered --fail-under=75

deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x docker-deploy.sh && sh $TRAVIS_BUILD_DIR/docker-deploy.sh
  on:
    tags: true
    repo: randsleadershipslack/destalinator
