# Name of your Slack -- just the aprt before '.slack.com'
slack_name: rands-leadership
# Name of environmental variable holding a valid Slackbot API token
slackbot_api_token_env_varname: SB_TOKEN
# Name of environmental variable holding a valid general-purpose API token
api_token_env_varname: API_TOKEN
# Days of silence before we warn a channel it's going to be archived
warn_threshold: 30
# Days of silence before we auto-archive a channel
archive_threshold: 60
earliest_archive_date: "2016-01-28"  # Do not archive before this date
#
# What emoji do people use to flag interesting messages?
interesting_emoji: "floppy_disk"
# How many people need to flag something before we think it's noteworthy?
interesting_threshold: 2
# What channel should we mention interesting things?
interesting_channel: "zmeta-flagged"
